[server] ##normal type
mode = "dev"
host = "localhost:8080"

[db] #data access object
[db.admin]
host = "mongodb://127.0.0.1:27017"
user = "junghoon"
pass = "jh2163"

[log]
level = "debug"
fpath = "./logs/go-loger"
msize = 2000
mage = 7
mbackup = 5